site_name: 2023-1 MeasureSoftGram
repo_url: https://github.com/fga-eps-mds/2023-1-MeasureSoftGram-Doc

theme:
    name: material
    features: navigation.tabs
    logo: assets/logo.svg
    favicon: assets/logo.svg
    palette:
        primary: blue grey

markdown_extensions:
    - admonition
    - pymdownx.details
    - pymdownx.superfences

nav:
    - Home: index.md
    - Manuais de Uso:
          - CLI: manual-de-uso/cli.md
    - Guia de contribuicao:
          - Como contribuir: guia_contribuicao/como_contribuir.md
          - Política de Branches: guia_contribuicao/branches.md
          - Política de Commits: guia_contribuicao/commits.md
          - Código de conduta: guia_contribuicao/CODE_OF_CONDUCT.md
    - Plano e monitoramento:
          - Plano de custos: documentos_de_projeto/plano_de_custos.md
          - Agenda e ferramentas: documentos_de_projeto/agenda_e_ferramentas.md
          - Estrutura analítica do projeto: documentos_de_projeto/eap.md
          - Roadmap: documentos_de_projeto/roadmap.md
    - Heatmap e Tabela de Conhecimento:
          - Heatmap: heatmap_knowledge_table/heatmap.md
          - Tabela de Conhecimento: heatmap_knowledge_table/knowledge_table.md
    - Documentação:
          - Arquitetura do projeto: documentos_de_projeto/arquitetura_do_projeto.md
          - Planejamento de Gerenciamento de Riscos: documentos_de_projeto/plano_de_riscos.md
    - Lean inception:
          - Introdução: lean_inception/Introducao.md
          - Visão do produto: lean_inception/visao_do_produto.md
          - É, Não É, Faz, Não Faz: lean_inception/E_Nao_E_Faz_Nao_Faz.md
          - Personas: lean_inception/Personas.md
          - Jornada de Usuario: lean_inception/Jornada_de_usuario.md
          - Brainstorming de Funcionalidades: lean_inception/Brainstorming_Funcionalidades.md
          - Revisão Técnica, de Negócio e de UX: lean_inception/Revisao_Tecnica.md
          - Sequenciador: lean_inception/Sequenciador.md
          - Canvas MVP: lean_inception/Canvas_MVP.md
          - Mural: lean_inception/Mural.md
    - Sprints:
          - sprint_12.05:  semanas-sprints/sprints/sprint_12.05.md   
          - Sprint_19.05:  semanas-sprints/sprints/sprint_19.05.md   
          - Sprint_29.05:  semanas-sprints/sprints/sprint_29.05.md   
          - Sprint_05.06:  semanas-sprints/sprints/sprint_05.06.md   
          - Sprint_12.06:  semanas-sprints/sprints/sprint_12.06.md   
          - Sprint_19.06:  semanas-sprints/sprints/sprint_19.06.md   
          - Sprint_26.06:  semanas-sprints/sprints/sprint_26.06.md   
