site_name: 2023-1 MeasureSoftGram
repo_url: https://github.com/fga-eps-mds/2023-1-MeasureSoftGram-Doc

theme:
    name: material
    features: navigation.tabs
    logo: assets/logo.svg
    favicon: assets/logo.svg
    palette:
        primary: blue grey

markdown_extensions:
    - admonition
    - pymdownx.details
    - pymdownx.superfences

nav:
    - Home: index.md
    - Guia de contribuicao:
      - Como contribuir: guia_contribuicao/como_contribuir.md
      - Política de Branches: guia_contribuicao/branches.md
      - Política de Commits: guia_contribuicao/commits.md
      - Código de conduta: guia_contribuicao/CODE_OF_CONDUCT.md
    - Plano e monitoramento:
      - Plano de custos: documentos_de_projeto/plano_de_custos.md
    - Heatmap e Tabela de Conhecimento:
      - Heatmap: heatmap_knowledge_table/heatmap.md
      - Tabela de Conhecimento: heatmap_knowledge_table/knowledge_table.md
    - Documentação:
       - Arquitetura do projeto: documentos_de_projeto/arquitetura_do_projeto.md
    - Lean inception: 
       - Mural: lean_inception/home.md
       - Visão do produto: lean_inception/visão_do_produto.md
       - É, Não É, Faz, Não Faz: lean_inception/É_Não_É_Faz_Não_Faz.md
       - Personas: lean_inception/Personas.md
       - Jornada de Usuario: lean_inception/Jornada_de_usuario.md
       - Brainstorming de Funcionalidades: lean_inception/Brainstorming_Funcionalidades.md
       - Revisão Técnica, de Negócio e de UX: lean_inception/Revisão_Técnica.md
       - Sequenciador: lean_inception/Sequenciador.md
       - Canvas MVP: lean_inception/Canvas_MVP.md